{{- if $.Values.ingressControllerToServices }}
{{- range $content := $.Values.ingressControllerToServices }}
{{- if $content.targetNamespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $content.sourceControllerName }}-controller-to-multiple-ns-egress-policy
  namespace: {{ $content.sourceControllerNamespace }}
  labels:
    platform: {{ $.Values.global.platform }}
    environment: {{ $.Values.global.environment }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ $content.sourceControllerName }}
  policyTypes:
  - Egress
  egress:
  {{- range $targetNamespace := $content.targetNamespaces }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $targetNamespace }}
      podSelector: {}
  {{- end }}
{{- range $targetNamespace := $content.targetNamespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-{{ $content.sourceControllerName }}-controller-to-{{ $targetNamespace }}-ns-ingress-policy
  namespace: {{ $targetNamespace }}
  labels:
    platform: {{ $.Values.global.platform }}
    environment: {{ $.Values.global.environment }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $content.sourceControllerNamespace }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ $content.sourceControllerName }}
{{- end }}
{{- else if $content.targetNamespace }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $content.sourceControllerName }}-controller-to-special-pods-of-{{ $content.targetNamespace }}-ns-egress-policy
  namespace: {{ $content.sourceControllerNamespace }}
  labels:
    platform: {{ $.Values.global.platform }}
    environment: {{ $.Values.global.environment }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ $content.sourceControllerName }}
  policyTypes:
  - Egress
  egress:
  {{- range $targetPod := $content.targetPods }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $content.targetNamespace }}
      podSelector:
        matchLabels:
          app: {{ $targetPod }}
  {{- end }}
{{- if eq (len $content.targetPods) 1 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-{{ $content.sourceControllerName }}-controller-to-{{ first $content.targetPods }}-pods-ingress-policy
  namespace: {{ $content.targetNamespace }}
  labels:
    platform: {{ $.Values.global.platform }}
    environment: {{ $.Values.global.environment }}
spec:
  podSelector:
    matchLabels:
      app: {{ first $content.targetPods }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $content.sourceControllerNamespace }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ $content.sourceControllerName }}
{{- else }}
{{- range $targetPod := $content.targetPods }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: from-{{ $content.sourceControllerName }}-controller-to-{{ $targetPod }}-pods-ingress-policy
  namespace: {{ $content.targetNamespace }}
  labels:
    platform: {{ $.Values.global.platform }}
    environment: {{ $.Values.global.environment }}
spec:
  podSelector:
    matchLabels:
      app: {{ $targetPod }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $content.sourceControllerNamespace }}
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ $content.sourceControllerName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}