{{- range $index, $namespace := (lookup "v1" "Namespace" "" "").items }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-policy
  namespace: {{ $namespace.metadata.name | quote }}
  labels:
    platform: {{ $.Values.global.platform }}
    environment: {{ $.Values.global.environment }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ $.Values.basicNetworking.vpcCidr }}
        except:
        {{- range $.Values.basicNetworking.blockCidrs }}
        - {{ . }}
        {{- end }}
  {{- if $.Values.basicNetworking.cloudApiCidr }}
  - to:
    - ipBlock:
        cidr: {{ $.Values.basicNetworking.cloudApiCidr }}
  {{- end }}
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: "kube-system"
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
{{- end }}